#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimepdeoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimepdeoperator1d_pg.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimetimederivoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimetimederivoperator1d_pg.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimelaplaceoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimelaplaceoperator1d_pg.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimeconvectionoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimereactionoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimereactionoperator1d_pg.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimeweightedconvectionoperator1d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/adaptivespacetimeweightedconvectionoperator1d_pg.h>
