//#include <lawa/methods/adaptive/algorithms/apply1d.h>
//#include <lawa/methods/adaptive/algorithms/apply2d.h>
#include <lawa/methods/adaptive/algorithms/lambdatilde.h>
#include <lawa/methods/adaptive/algorithms/linearsystemsolvers.h>
#include <lawa/methods/adaptive/algorithms/localrefinement.h>
#include <lawa/methods/adaptive/algorithms/multitreeoperations.h>
#include <lawa/methods/adaptive/algorithms/security_zone.h>
#include <lawa/methods/adaptive/algorithms/thresh.h>
#include <lawa/methods/adaptive/algorithms/weightedapply1d.h>
