#include <lawa/operators/pdeoperators1d/convectionoperator1d.h>
#include <lawa/operators/pdeoperators1d/helmholtzoperator1d.h>
#include <lawa/operators/pdeoperators1d/identityoperator1d.h>
#include <lawa/operators/pdeoperators1d/laplaceoperator1d.h>
#include <lawa/operators/pdeoperators1d/pdeoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedhelmholtzoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedidentityoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedlaplaceoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedpdeoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedconvectionoperator1d.h>
#include <lawa/operators/pdeoperators1d/weightedconvectionoperator1d_pg.h>
